<a href="https://colab.research.google.com/github/Prathamesh-chougale-17/Machine-Learning-course/blob/main/Preprocessing/Encoding-the-dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BASIC

 Importing the libraries




In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import the dataset

In [10]:
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:,:-1].values
# in iloc [:(selecting all rows),:-1(selecting all coloum except last one)]
Y = dataset.iloc[:,-1]
# in this one [:(selecting all rows),-1 (selecting last column)]


In [11]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
print(Y)

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


Taking care of missing data

In [ ]:
# we can handle missing values values by many ways
# 1. if dataset have less number of missing values or 1% of missing values then we can remove those
# 2. we can take average of other data and replace it with the null values

# sciket-learn is one of the best data science library that include many data-preprocessing tools and for handling the missing data


In [14]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')
imputer.fit(X[:,1:3])
# fit will find average of the column and it only accept all Numbericals values in subdataset (X)
X[:,1:3]=imputer.transform(X[:,1:3])
# transform will replace the nan column

In [15]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding categorical data

Encoding the Independent Variable

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [20]:
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [21]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
